// registry/new-york/ui/textarea/textarea.tsx
import React, { useId } from 'react';
import styles from './textarea.module.scss';

export interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  label?: string;
  error?: string;
  helperText?: string;
  required?: boolean;
}

const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  (
    {
      className = '',
      label,
      error,
      helperText,
      required,
      id: providedId,
      ...props
    },
    ref
  ) => {
    const generatedId = useId();
    const id = providedId || generatedId;
    const errorId = `${id}-error`;
    const helperId = `${id}-helper`;

    return (
      <div className={styles.textareaWrapper}>
        {label && (
          <label
            htmlFor={id}
            className={`${styles.label} ${required ? styles.required : ''}`}
          >
            {label}
          </label>
        )}
        <textarea
          ref={ref}
          id={id}
          className={`${styles.textarea} ${error ? styles.error : ''} ${className}`}
          aria-invalid={!!error}
          aria-describedby={error ? errorId : helperText ? helperId : undefined}
          {...props}
        />
        {error && (
          <span id={errorId} className={styles.errorText}>
            {error}
          </span>
        )}
        {!error && helperText && (
          <span id={helperId} className={styles.helperText}>
            {helperText}
          </span>
        )}
      </div>
    );
  }
);

Textarea.displayName = 'Textarea';

export { Textarea };
export default Textarea;

// packages/vue/src/components/textarea/textarea.tsx
import { defineComponent, computed, h } from 'vue';
import { getTextareaIds, getTextareaAriaProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/textarea.module.scss';

let textareaCounter = 0;

export const TTextarea = defineComponent({
  name: 'TTextarea',
  props: {
    label: String,
    error: String,
    helperText: String,
    required: { type: Boolean, default: false },
    id: String,
    placeholder: String,
    modelValue: String,
    disabled: { type: Boolean, default: false },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const textareaId = computed(() => props.id || `tile-textarea-${++textareaCounter}`);
    const ids = computed(() => getTextareaIds(textareaId.value));
    const ariaProps = computed(() => getTextareaAriaProps(ids.value, props.error, props.helperText));

    function onInput(event: Event) {
      emit('update:modelValue', (event.target as HTMLTextAreaElement).value);
    }

    return () => {
      const children: any[] = [];

      if (props.label) {
        children.push(
          h('label', {
            for: textareaId.value,
            class: [styles.label, props.required ? styles.required : ''],
          }, props.label)
        );
      }

      children.push(
        h('textarea', {
          id: textareaId.value,
          class: [styles.textarea, props.error ? styles.error : ''],
          value: props.modelValue,
          placeholder: props.placeholder,
          disabled: props.disabled,
          'aria-invalid': ariaProps.value['aria-invalid'],
          'aria-describedby': ariaProps.value['aria-describedby'],
          onInput,
        })
      );

      if (props.error) {
        children.push(
          h('span', { id: ids.value.error, class: styles.errorText }, props.error)
        );
      } else if (props.helperText) {
        children.push(
          h('span', { id: ids.value.helper, class: styles.helperText }, props.helperText)
        );
      }

      return h('div', { class: styles.textareaWrapper }, children);
    };
  },
});

export default TTextarea;
