// packages/react/src/components/button/button.tsx
import React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { getButtonStyleKeys, isButtonDisabled } from '@tile-ui/core';
import type { ButtonBaseProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/button.module.scss';

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement>, ButtonBaseProps {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
	({ className = '', variant = 'default', size = 'default', asChild = false, loading = false, disabled, children, ...props }, ref) => {
		const Comp = asChild ? Slot : 'button';
		const styleKeys = getButtonStyleKeys(variant, size);

		const classes = [styles[styleKeys.base], styles[styleKeys.variant], styles[styleKeys.size], className].filter(Boolean).join(' ');

		return (
			<Comp ref={ref} className={classes} disabled={isButtonDisabled(disabled, loading)} {...props}>
				{loading && (
					<svg
						className={styles.spinner}
						xmlns="http://www.w3.org/2000/svg"
						width="16"
						height="16"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						strokeWidth="2"
						strokeLinecap="round"
						strokeLinejoin="round">
						<circle cx="12" cy="12" r="10" />
					</svg>
				)}
				{children}
			</Comp>
		);
	},
);

Button.displayName = 'Button';

export { Button };
export default Button;

// packages/vue/src/components/button/button.tsx
import { defineComponent, computed, h, type PropType } from 'vue';
import { getButtonStyleKeys, isButtonDisabled } from '@tile-ui/core';
import type { ButtonVariant, ButtonSize } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/button.module.scss';

export const TButton = defineComponent({
	name: 'TButton',
	props: {
		variant: {
			type: String as PropType<ButtonVariant>,
			default: 'default',
		},
		size: {
			type: String as PropType<ButtonSize>,
			default: 'default',
		},
		loading: { type: Boolean, default: false },
		disabled: { type: Boolean, default: false },
		type: {
			type: String as PropType<'button' | 'submit' | 'reset'>,
			default: 'button',
		},
	},
	setup(props, { slots }) {
		const styleKeys = computed(() => getButtonStyleKeys(props.variant, props.size));
		const computedDisabled = computed(() => isButtonDisabled(props.disabled, props.loading));
		const classes = computed(() => [styles[styleKeys.value.base], styles[styleKeys.value.variant], styles[styleKeys.value.size]]);

		return () => {
			const children: any[] = [];
			if (props.loading) {
				children.push(
					h(
						'svg',
						{
							class: styles.spinner,
							xmlns: 'http://www.w3.org/2000/svg',
							width: '16',
							height: '16',
							viewBox: '0 0 24 24',
							fill: 'none',
							stroke: 'currentColor',
							'stroke-width': '2',
							'stroke-linecap': 'round',
							'stroke-linejoin': 'round',
						},
						[h('circle', { cx: '12', cy: '12', r: '10' })],
					),
				);
			}
			if (slots.default) {
				children.push(slots.default());
			}
			return h(
				'button',
				{
					class: classes.value,
					disabled: computedDisabled.value,
					type: props.type,
				},
				children,
			);
		};
	},
});

export default TButton;
