// registry/new-york/ui/input/input.tsx
import React, { useId } from 'react';
import styles from './input.module.scss';

export interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  label?: string;
  error?: string;
  helperText?: string;
  required?: boolean;
}

const Input = React.forwardRef<HTMLInputElement, InputProps>(
  (
    {
      className = '',
      label,
      error,
      helperText,
      required,
      id: providedId,
      type = 'text',
      ...props
    },
    ref
  ) => {
    const generatedId = useId();
    const id = providedId || generatedId;
    const errorId = `${id}-error`;
    const helperId = `${id}-helper`;

    return (
      <div className={styles.inputWrapper}>
        {label && (
          <label
            htmlFor={id}
            className={`${styles.label} ${required ? styles.required : ''}`}
          >
            {label}
          </label>
        )}
        <input
          ref={ref}
          id={id}
          type={type}
          className={`${styles.input} ${error ? styles.error : ''} ${className}`}
          aria-invalid={!!error}
          aria-describedby={error ? errorId : helperText ? helperId : undefined}
          {...props}
        />
        {error && (
          <span id={errorId} className={styles.errorText}>
            {error}
          </span>
        )}
        {!error && helperText && (
          <span id={helperId} className={styles.helperText}>
            {helperText}
          </span>
        )}
      </div>
    );
  }
);

Input.displayName = 'Input';

export { Input };
export default Input;

// packages/vue/src/components/input/input.tsx
import { defineComponent, computed, h } from 'vue';
import { getInputIds, getInputAriaProps } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/input.module.scss';

let inputCounter = 0;

export const TInput = defineComponent({
  name: 'TInput',
  props: {
    label: String,
    error: String,
    helperText: String,
    required: { type: Boolean, default: false },
    id: String,
    type: { type: String, default: 'text' },
    placeholder: String,
    modelValue: String,
    disabled: { type: Boolean, default: false },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const inputId = computed(() => props.id || `tile-input-${++inputCounter}`);
    const ids = computed(() => getInputIds(inputId.value));
    const ariaProps = computed(() => getInputAriaProps(ids.value, props.error, props.helperText));

    function onInput(event: Event) {
      emit('update:modelValue', (event.target as HTMLInputElement).value);
    }

    return () => {
      const children: any[] = [];

      if (props.label) {
        children.push(
          h('label', {
            for: inputId.value,
            class: [styles.label, props.required ? styles.required : ''],
          }, props.label)
        );
      }

      children.push(
        h('input', {
          id: inputId.value,
          type: props.type,
          class: [styles.input, props.error ? styles.error : ''],
          value: props.modelValue,
          placeholder: props.placeholder,
          disabled: props.disabled,
          'aria-invalid': ariaProps.value['aria-invalid'],
          'aria-describedby': ariaProps.value['aria-describedby'],
          onInput,
        })
      );

      if (props.error) {
        children.push(
          h('span', { id: ids.value.error, class: styles.errorText }, props.error)
        );
      } else if (props.helperText) {
        children.push(
          h('span', { id: ids.value.helper, class: styles.helperText }, props.helperText)
        );
      }

      return h('div', { class: styles.inputWrapper }, children);
    };
  },
});

export default TInput;
