// apps/vue/components/docs-toc.tsx
import { computed, defineComponent, onBeforeUnmount, onMounted, PropType, ref } from 'vue';

type TocItem = {
	title?: string;
	url: string;
	depth: number;
};

export const VueDocsToc = defineComponent({
	name: 'VueDocsToc',
	props: {
		toc: {
			type: Array as PropType<TocItem[]>,
			required: true,
		},
		variant: {
			type: String as PropType<'list' | 'dropdown'>,
			default: 'list',
		},
	},
	setup(props) {
		const open = ref(false);
		const activeHeading = ref<string | null>(null);
		const container = ref<HTMLElement | null>(null);
		let observer: IntersectionObserver | null = null;

		const links = computed(() =>
			props.toc.map((item) => ({
				...item,
				title: item.title ?? decodeURIComponent(item.url.replace(/^#/, '').replace(/-/g, ' ')),
			})),
		);

		onMounted(() => {
			observer = new IntersectionObserver(
				(entries) => {
					for (const entry of entries) {
						if (entry.isIntersecting) {
							activeHeading.value = entry.target.id;
						}
					}
				},
				{ rootMargin: '0% 0% -80% 0%' },
			);

			for (const item of props.toc) {
				const element = document.getElementById(item.url.replace(/^#/, ''));
				if (element) observer.observe(element);
			}

			const handlePointerDown = (event: MouseEvent) => {
				if (!container.value?.contains(event.target as Node)) {
					open.value = false;
				}
			};

			const handleEscape = (event: KeyboardEvent) => {
				if (event.key === 'Escape') open.value = false;
			};

			document.addEventListener('mousedown', handlePointerDown);
			document.addEventListener('keydown', handleEscape);

			onBeforeUnmount(() => {
				document.removeEventListener('mousedown', handlePointerDown);
				document.removeEventListener('keydown', handleEscape);
				observer?.disconnect();
			});
		});

		return () => {
			if (!links.value.length) return null;

			if (props.variant === 'dropdown') {
				return (
					<div ref={container} class="docs-toc-mobile">
						<button
							type="button"
							class="docs-toc-mobile__trigger"
							aria-expanded={open.value}
							onClick={() => {
								open.value = !open.value;
							}}>
							<span class="docs-toc-mobile__icon" aria-hidden="true">
								<svg viewBox="0 0 16 16" fill="none">
									<path d="M2.5 4.5H13.5M2.5 8H13.5M2.5 11.5H9.5" stroke="currentColor" stroke-width="1.25" stroke-linecap="round" />
								</svg>
							</span>
							On This Page
						</button>
						{open.value ? (
							<div class="docs-toc-mobile__content">
								{links.value.map((item) => (
									<a
										key={item.url}
										href={item.url}
										class="docs-toc__link"
										data-active={item.url === `#${activeHeading.value}`}
										data-depth={item.depth}
										onClick={() => {
											open.value = false;
										}}>
										{item.title}
									</a>
								))}
							</div>
						) : null}
					</div>
				);
			}

			return (
				<div class="docs-toc">
					<p class="docs-toc__title">On This Page</p>
					{links.value.map((item) => (
						<a key={item.url} href={item.url} class="docs-toc__link" data-active={item.url === `#${activeHeading.value}`} data-depth={item.depth}>
							{item.title}
						</a>
					))}
				</div>
			);
		};
	},
});

// apps/react/components/docs-toc.tsx
'use client';

import { useEffect, useMemo, useRef, useState } from 'react';

type TocItem = {
	title?: string;
	url: string;
	depth: number;
};

function useActiveItem(itemIds: string[]) {
	const [activeId, setActiveId] = useState<string | null>(null);

	useEffect(() => {
		const observer = new IntersectionObserver(
			(entries) => {
				for (const entry of entries) {
					if (entry.isIntersecting) {
						setActiveId(entry.target.id);
					}
				}
			},
			{ rootMargin: '0% 0% -80% 0%' },
		);

		for (const id of itemIds) {
			const element = document.getElementById(id);
			if (element) {
				observer.observe(element);
			}
		}

		return () => {
			for (const id of itemIds) {
				const element = document.getElementById(id);
				if (element) {
					observer.unobserve(element);
				}
			}
			observer.disconnect();
		};
	}, [itemIds]);

	return activeId;
}

function TocLinks({
	toc,
	activeHeading,
	onNavigate,
}: {
	toc: TocItem[];
	activeHeading: string | null;
	onNavigate?: () => void;
}) {
	return toc.map((item) => (
		// Fallback text keeps TOC visible even if source titles are non-string.
		<a
			key={item.url}
			href={item.url}
			className="docs-toc__link"
			data-active={item.url === `#${activeHeading}`}
			data-depth={item.depth}
			onClick={onNavigate}>
			{item.title ?? item.url.replace(/^#/, '').replace(/-/g, ' ')}
		</a>
	));
}

export function DocsTableOfContents({
	toc,
	variant = 'list',
}: {
	toc: TocItem[];
	variant?: 'list' | 'dropdown';
}) {
	const [open, setOpen] = useState(false);
	const containerRef = useRef<HTMLDivElement | null>(null);
	const itemIds = useMemo(() => toc.map((item) => item.url.replace('#', '')), [toc]);
	const activeHeading = useActiveItem(itemIds);

	useEffect(() => {
		if (!open) {
			return;
		}

		function handlePointerDown(event: MouseEvent) {
			if (!containerRef.current?.contains(event.target as Node)) {
				setOpen(false);
			}
		}

		function handleEscape(event: KeyboardEvent) {
			if (event.key === 'Escape') {
				setOpen(false);
			}
		}

		document.addEventListener('mousedown', handlePointerDown);
		document.addEventListener('keydown', handleEscape);

		return () => {
			document.removeEventListener('mousedown', handlePointerDown);
			document.removeEventListener('keydown', handleEscape);
		};
	}, [open]);

	if (!toc.length) {
		return null;
	}

	if (variant === 'dropdown') {
		return (
			<div ref={containerRef} className="docs-toc-mobile">
				<button
					type="button"
					className="docs-toc-mobile__trigger"
					aria-expanded={open}
					aria-haspopup="menu"
					onClick={() => setOpen((value) => !value)}>
					<span className="docs-toc-mobile__icon" aria-hidden="true">
						<svg viewBox="0 0 16 16" fill="none">
							<path d="M2.5 4.5H13.5M2.5 8H13.5M2.5 11.5H9.5" stroke="currentColor" strokeWidth="1.25" strokeLinecap="round" />
						</svg>
					</span>
					On This Page
				</button>
				{open ? (
					<div className="docs-toc-mobile__content" role="menu">
						<TocLinks toc={toc} activeHeading={activeHeading} onNavigate={() => setOpen(false)} />
					</div>
				) : null}
			</div>
		);
	}

	return (
		<div className="docs-toc">
			<p className="docs-toc__title">On This Page</p>
			<TocLinks toc={toc} activeHeading={activeHeading} />
		</div>
	);
}
