// packages/vue/src/components/label/label.tsx
import { defineComponent, computed, h } from 'vue';
import { getLabelClassKeys } from '@tile-ui/core';
import styles from '@tile-ui/styles/scss/components/label.module.scss';

export const TLabel = defineComponent({
	name: 'TLabel',
	props: {
		required: { type: Boolean, default: false },
		htmlFor: String,
	},
	setup(props, { slots }) {
		const classKeys = computed(() => getLabelClassKeys(props.required));
		const classes = computed(() => [styles[classKeys.value.base], classKeys.value.required ? styles[classKeys.value.required] : '']);

		return () => h('label', { class: classes.value, for: props.htmlFor }, slots.default?.());
	},
});

export default TLabel;

// registry/tile-ui/label/label.tsx
import React from 'react';
import * as LabelPrimitive from '@radix-ui/react-label';
import styles from './label.module.scss';

// --- Inlined from @tile-ui/core ---
interface LabelBaseProps {
  required?: boolean;
}

function getLabelClassKeys(required?: boolean) {
  return {
    base: 'label',
    required: required ? 'required' : undefined,
  };
}
// --- End inlined ---

export interface LabelProps
  extends React.LabelHTMLAttributes<HTMLLabelElement>,
    LabelBaseProps {}

const Label = React.forwardRef<HTMLLabelElement, LabelProps>(
  ({ className = '', required, children, ...props }, ref) => {
    const classKeys = getLabelClassKeys(required);

    return (
      <LabelPrimitive.Root
        ref={ref}
        className={`${styles[classKeys.base]} ${classKeys.required ? styles[classKeys.required] : ''} ${className}`}
        {...props}
      >
        {children}
      </LabelPrimitive.Root>
    );
  }
);

Label.displayName = 'Label';

export { Label };
export default Label;
